### ISSUE TITLE
Could not create an instance of type org.multimc.quickmod.QuickMod

### ISSUE THREAD

**Issue by scaytrase** [robotbrain/quickmod-gradle#3]
Now it successfully resolves 1.3.2 dependency but fails. Gradle cache was cleared.

```
15:26:25.764 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'mc_mod_CustomOreGen'.
15:26:25.764 [ERROR] [org.gradle.BuildExceptionReporter] > Could not create an instance of type org.multimc.quickmod.QuickMod.
```

```
15:26:25.766 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:26:25.766 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'mc_mod_CustomOreGen'.
15:26:25.766 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
15:26:25.766 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:177)
15:26:25.767 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:507)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:82)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:26:25.769 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:46)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:26:25.770 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:37)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type org.multimc.quickmod.QuickMod.
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:41)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ReflectiveNamedDomainObjectFactory.create(ReflectiveNamedDomainObjectFactory.java:38)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.FactoryNamedDomainObjectContainer.doCreate(FactoryNamedDomainObjectContainer.java:100)
15:26:25.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:57)
15:26:25.772 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:52)
15:26:25.772 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:39)
15:26:25.772 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:78)
15:26:25.772 [ERROR] [org.gradle.BuildExceptionReporter]        at build_1e436c2e1ufc75im0mq8kjssg0$_run_closure3.doCall(/root/workspace/mc_mod_CustomOreGen/build.gradle:63)
15:26:25.772 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:68)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:50)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:213)
15:26:25.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        at build_1e436c2e1ufc75im0mq8kjssg0.run(/root/workspace/mc_mod_CustomOreGen/build.gradle:62)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        ... 33 more
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        at org.multimc.quickmod.QuickMod.<init>(QuickModsExtension.groovy:9)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:39)
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        ... 53 more
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]        ... 55 more
15:26:25.774 [ERROR] [org.gradle.BuildExceptionReporter]

```

**Comment by robotbrain** [comment]
...im confused
add
```
classpath org.codehaus.groovy:groovy-backports-compat23:2.3.5
```

under the other classpath lines and see if that fixes it

**Comment by scaytrase** [comment]
Yes, this works, thanks. Should I wait for you fix, or this is misconfiguration of project I'm building?

**Comment by robotbrain** [comment]
its caused by differences in gradle's groovy version, Ill add that line to the example
